# Site settings
title: Mister Sittler Writes Code
header-img: img/home-bg.png
email: neil@stickflower.com
copyright_name: mistersittler
description: > # this means to ignore newlines until "baseurl:"
  The evolution of my career continues here...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mistersittler
learn_profile: mistersittler
email_username: neil@stickflower.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
